### PR TITLE
IoT Edge WG Whitepaper - Edge Native Application Principles

### PR DESCRIPTION
**Pull request by joerober**
PR adds 
- cncf/tag-runtime/wg/whitepapers folder
- Draft of IoT Edge WG whitepaper Edge Native Application Principles

/cc @kate-goldenring

### CODE REVIEW

**Comment by kad** [comment]
two suggestions:
1. squash commits
2. cleanup things where spaces added in the end of the line.

**Comment by dejanb** [comment]
Looks good

**Comment by cantbewong** [comment]
lgtm

**Comment by kate-goldenring** [comment]
@raravena80 do you mind pressing merge? Excited about all the work that led up to this! Thank you, @joerober!

**Comment by raravena80** [comment]
@kate-goldenring done. Thx!

**Pull request merged**
