### PR TITLE
Update leads

### PR DESCRIPTION
**Pull request by raravena80**
Update leads for the Working Group

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
Congrats, @ronaldpetty and @zanetworker! 🎉

**Comment by nikhita** [comment]
I tried to find a process for how WG leads should be approved but couldn't find any so I created this issue - https://github.com/cncf/toc/issues/1308.

I know that there have been discussions on slack about this privately but it'll be important for us to have a linkable record of approval too.

For now, can we have at least one other TAG Runtime lead (@rajaskakodkar, @srust or @miao0miao) and 2 other WG AI leads  (@cathyhongzhang, @rootfs) at least retroactively +1 on this thread to have a public record of approval?

**Comment by srust** [comment]
+1 from @srust

**Comment by rootfs** [comment]
+1, well deserved! Looking forward to more impactful collaborations for the WG.

**Pull request merged**
