### PR TITLE
Update AI WG leads

### PR DESCRIPTION
**Pull request by Ghatage**
Requesting nomination to join AI Working group as per discussion [here](https://github.com/cncf/tag-runtime/pull/133#issuecomment-2081878244).
I have also sent an email to all the reviewers with more details.

### CODE REVIEW

**Comment by Ghatage** [comment]
@srust @cathyhongzhang PTAL

**Review by rajaskakodkar — CHANGES_REQUESTED** [review]
@Ghatage can you please provide more context on your contributions and efforts to make a case for you to be added as a lead?

**Comment by Ghatage** [comment]
Hi @rajaskakodkar, folks of the TAG Runtime and AI WG Tech Leads,

I'm Anup Ghatage, I work as a Lead Software Engineer at Salesforce.
I am writing to you for my nomination to join the CNCF AI Working Group as a Tech lead at the suggestion of Taylor Dolezal (in CC) and to you particularly as per the guidelines laid out [here](https://github.com/cncf/tag-runtime/pull/133#issuecomment-2081878244).

At Salesforce, we run 100s of clusters, 10k pods and innumerable k8s jobs - all in a unique cloud native environment that we have worked closely to develop with a joint partnership with AWS and Ali Cloud to name a few. I believe this makes us - if not the largest - one of the largest kubernetes deployments in both of the popular cloud providers.
With the advent of AI, we have been thinking about how to integrate it within our existing ecosystem in a secure and scalable manner.
As a part of that work [I've given a talk at the recent IEEE Security and Privacy Symposium](https://www.linkedin.com/posts/ghatageanup_had-the-pleasure-of-sharing-my-latest-innovation-activity-7201240451557777410-xC8_?utm_source=share&utm_medium=member_desktop) discussing these specifications challenges.

Salesforce has had a long history of contributing back to the open source community. I am also one of the committers of several Apache Foundation projects where we share knowledge via code contributions and talks. While new to CNCF from an organizational perspective, I was introduced to it by [Priyanka Sharma and Taylor after my talk at the Ollama Local AI Meetup](https://www.linkedin.com/posts/pritianka_things-are-moving-so-much-in-the-ai-space-activity-7163753290877317122-rCBg?utm_source=share&utm_medium=member_desktop).
The goals of the working group and what we are trying to achieve are very common and as one of the largest end users of CNCF technology, we are acutely aware of the challenges.
I have already taken the initiative to familiarize myself with the group's objectives and ongoing projects by going through the mailing list and adding myself to the relevant slack channels etc.

Please consider my humble nomination to join this working group via [this github pull request](https://github.com/cncf/tag-runtime/pull/167).

**Comment by srust** [comment]
Hi @Ghatage, the best way to start and join the AI working group is simply to join in! Feel free to join the slack channel, and attend meetings, and get to know everyone. Over time and being part of the community, you would naturally move towards a tech lead status. But you certainly don't need to become a tech lead in order to join the community and working group and start contributing.

The slack and meeting info is here: https://tag-runtime.cncf.io/wgs/cnaiwg/

That's going to be the best way for you to get started and join in. Thanks!

**Comment by Ghatage** [comment]
Will do, thanks!

**Pull request closed without merging**
