### PR TITLE
add cnai news and the first post

### PR DESCRIPTION
**Pull request by zanetworker**
This PR adds a section for news to encourage contribution and expose the rest of the community to the work the WG is doing.

### CODE REVIEW

**Comment by zanetworker** [comment]
@cjyabraham do you know why I am getting large description font? Any ideas how to make it smaller / normal?
image

**Comment by cjyabraham** [comment]
What you're seeing there is the style we use throughout the site for content in description fields. If you want that paragraph to be normal size then you could move it out of the description field into the regular body text of the page.

**Comment by zanetworker** [comment]
@raravena80 FYI.

**Comment by zanetworker** [comment]
let me know if other changes are needed.

**Review by raravena80 — APPROVED** [review]
lgtm! Thanks for creating it.

**Pull request merged**
