### PR TITLE
Translate CNCF Cloud Native AI white paper into Japanese

### PR DESCRIPTION
**Pull request by kenta-iijima**
I am translating the CNCF Cloud Native AI white paper into Japanese. 
For now, I have translated the Executive Summary section. 
If it looks okay, I will continue.
If someone else can work on it, let’s work together.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
If this PR is a Work in Progress, I think it’s better to convert it to a Draft PR :)

FYI: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Review by raravena80 — APPROVED** [review]
lgtm.  FYI. I don't read Japanese, so I'm assuming the content is good.

**Comment by Okabe-Junya** [comment]
Thanks @raravena80 to take a look :)

I opened the issue to make our working easier to understand. See #152 

Additionally, It might be a bit hard for the maintainers to review all the l10n PRs. Do you think it would be reasonable to grant "write access" to this repo to a few Japanese l10n reviewers, including me? (If so, I will open a PR in cncf/people.)

**Comment by Okabe-Junya** [comment]
Thank you, As far as I know, no one else is working on the l10n of this white paper.

When you're ready to move forward with this PR, please remove the Draft status and mention me :)

**Review by Okabe-Junya — APPROVED** [review]
Deploy preview: [link](https://deploy-preview-150--tag-runtime.netlify.app/ja/wgs/cnaiwg/whitepapers/cloudnativeai/)

Thanks!! From the perspective of Japanese localization, LGTM :)

**Review by Okabe-Junya — APPROVED** [review]
LGTM! thanks!

**Comment by Okabe-Junya** [comment]
@raravena80 

From a localization perspective, LGTM. Please merge this PR.

**Review by rajaskakodkar — APPROVED** [review]
I don't read Japanese too but assuming that the content is good!

**Comment by rajaskakodkar** [comment]
@kenta-iijima all the commits have to be signed. We are good to merge after you sign them

**Comment by rajaskakodkar** [comment]
thank you @kenta-iijima! I don't have the merge button karma. @raravena80 should be able to help

**Pull request merged**
