### PR TITLE
Update charter info

### PR DESCRIPTION
**Pull request by mauromorales**
- Add myself as co-chair
- update the time of the meeting
- use simple link to community inviter

### CODE REVIEW

**Comment by mauromorales** [comment]
@rajaskakodkar @nikhita @miao0miao @stmcginnis 

Hi everyone 👋  just reaching out to get this merged or get some feedback, thanks!

**Review by srust — APPROVED** [review]

**Review by raravena80 — COMMENTED** [review]
Thanks!

**Comment by raravena80** [comment]
FWIW. This had to be reviewed by the TOC liaison. In lieu that we already merged the PR, can we get a confirmation from either @nikhita @angellk, @dims?


cc: @rajaskakodkar

**Comment by rajaskakodkar** [comment]
Yes, agree to @raravena80's comment! ^^^

**Comment by angellk** [comment]
Hi @raravena80 @rajaskakodkar - I don't see a nomination in the TOC repo for a new TAG Runtime Chair. Could you please either link the vote here - or revert this merge and nominate through the proper process:

https://github.com/cncf/toc/issues/new?template=tag-leadership-nomination.yaml

**Comment by srust** [comment]
This is for a chair of the special purpose OS working group, a tag runtime working group -- not for a tag runtime chair. Thanks!

**Comment by angellk** [comment]
@srust please review my edited comment - still need to submit a proper nomination for a new WG Chair

**Comment by raravena80** [comment]
> Is there a WG Chair nomination issue that you can link? If not, please revert and have a nomination drafted for review/approval.

@mauromorales can you open an issue on this repo with the nomination?

**Comment by raravena80** [comment]
Revert PR https://github.com/cncf/tag-runtime/pull/197

**Comment by srust** [comment]
Yep sorry for the trouble. Thanks for following the process @mauromorales !

**Comment by mauromorales** [comment]
@srust @raravena80 @angellk happy to open the issue, is there a special procedure for this? do you have some documentation for it? or just me saying I nominate myself :P

**Comment by sfc-gh-raravena** [comment]
You can just nominate yourself with a quick bio and why you like to be a chair (maybe how that aligns with your interests)

**Comment by mauromorales** [comment]
@sfc-gh-raravena @srust @raravena80 @angellk here's the open issue https://github.com/cncf/tag-runtime/issues/199. 

Please let me know if there's anything else needed, thanks!

**Pull request merged**
